apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-account-service
  template:
    metadata:
      labels:
        app: bank-account-service
    spec:
      containers:
        - name: account-service
          image: my-registry/bank-account-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bank-config
            - secretRef:
                name: bank-secret
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bank-account-service
spec:
  ports:
    - port: 8082
  selector:
    app: bank-account-service
