apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-user-service
  template:
    metadata:
      labels:
        app: bank-user-service
    spec:
      containers:
        - name: user-service
          image: my-registry/bank-user-service:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bank-config
            - secretRef:
                name: bank-secret
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bank-user-service
spec:
  ports:
    - port: 8081
  selector:
    app: bank-user-service
