spring:
  config:
    import: optional:file:.env[.properties], optional:file:../.env[.properties]
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://${DB_HOST:bank-mysql-accounts}:3306/bank_accounts
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:bank-kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8082

user-service:
  url: ${USER_SERVICE_URL:http://bank-user-service:8081}

internal:
  service-secret: ${INTERNAL_SERVICE_SECRET:my_internal_service_secret_key}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:bank-zipkin}:9411/api/v2/spans"

logging:
  file:
    name: ${LOG_PATH:./logs}/${spring.application.name}.log
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
